drop table if exists curso CASCADE 
drop table if exists perfil CASCADE 
drop table if exists resposta CASCADE 
drop table if exists topico CASCADE 
drop table if exists usuario CASCADE 
drop table if exists usuario_perfis CASCADE 
create table curso (id bigint generated by default as identity, categoria varchar(255) not null, nome varchar(255) not null, primary key (id))
create table perfil (id bigint generated by default as identity, nome varchar(255) not null, primary key (id))
create table resposta (id bigint generated by default as identity, data_criacao timestamp not null, mensagem varchar(500) not null, solucao boolean not null, autor_id bigint, topico_id bigint, primary key (id))
create table topico (id bigint generated by default as identity, data_criacao timestamp not null, mensagem varchar(500) not null, status varchar(255) not null, titulo varchar(255) not null, autor_id bigint, curso_id bigint, primary key (id))
create table usuario (id bigint generated by default as identity, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id))
create table usuario_perfis (usuario_id bigint not null, perfis_id bigint not null)
alter table resposta add constraint FK9999kvnmdq63ah7imctrl06r7 foreign key (autor_id) references usuario
alter table resposta add constraint FKltuv9rkfjtlmn8b0rb3wdbjsv foreign key (topico_id) references topico
alter table topico add constraint FKsk04hscorwqdymnafg8882v64 foreign key (autor_id) references usuario
alter table topico add constraint FKcaaogjo0ynd54updie6kdpxd1 foreign key (curso_id) references curso
alter table usuario_perfis add constraint FK7bhs80brgvo80vhme3u8m6ive foreign key (perfis_id) references perfil
alter table usuario_perfis add constraint FKs91tgiyagbilt959wbufiphgc foreign key (usuario_id) references usuario