create table curso (id bigint generated by default as identity, categoria varchar(255) not null, nome varchar(255) not null, primary key (id));
create table resposta (id bigint generated by default as identity, data_criacao timestamp not null, mensagem varchar(500) not null, solucao boolean not null, autor_id bigint, topico_id bigint, primary key (id));
create table topico (id bigint generated by default as identity, data_criacao timestamp not null, mensagem varchar(500) not null, status varchar(255) not null, titulo varchar(255) not null, autor_id bigint, curso_id bigint, primary key (id));
create table usuario (id bigint generated by default as identity, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id));
alter table resposta add constraint FK9999kvnmdq63ah7imctrl06r7 foreign key (autor_id) references usuario;
alter table resposta add constraint FKltuv9rkfjtlmn8b0rb3wdbjsv foreign key (topico_id) references topico;
alter table topico add constraint FKsk04hscorwqdymnafg8882v64 foreign key (autor_id) references usuario;
alter table topico add constraint FKcaaogjo0ynd54updie6kdpxd1 foreign key (curso_id) references curso;
